## Deliverable 2. Create a Customer Travel Destinations Map.

In [88]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import csv
import numpy as np


# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [89]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_database.csv")
city_data_df.head(10)

,City ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Current Description,Date
0,0,Saint-Leu,-21.1500,55.2833,70.63,68,30,14.25,RE,scattered clouds,2021-05-21 23:05:46
1,1,Rudnogorsk,57.2639,103.7519,38.50,41,63,2.26,RU,broken clouds,2021-05-21 23:05:46
2,2,Sao Joao Da Barra,-21.6403,-41.0511,73.09,87,7,8.99,BR,clear sky,2021-05-21 23:04:47
3,3,Verkhoyansk,67.5447,133.3850,38.30,54,23,7.65,RU,few clouds,2021-05-21 23:05:46
4,4,Bealanana,-14.5500,48.7333,54.00,96,64,3.71,MG,broken clouds,2021-05-21 23:05:47
5,5,Hermanus,-34.4187,19.2345,52.90,66,24,4.63,ZA,few clouds,2021-05-21 23:05:47
6,6,Vanimo,-2.6741,141.3028,81.61,81,100,2.39,PG,overcast clouds,2021-05-21 23:05:47
7,7,Shenjiamen,29.9576,122.2980,64.71,91,100,5.66,CN,light rain,2021-05-21 23:05:47
8,8,Aykhal,66.0000,111.5000,28.40,86,58,3.09,RU,broken clouds,2021-05-21 23:05:48
9,9,Camana,-16.6228,-72.7111,64.38,83,92,10.11,PE,overcast clouds,2021-05-21 23:05:48

In [90]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input('What is the minimum temperature would you prefer for your trip?'))
max_temp = float(input('What is the maximum temperation would you prefer for your trip?'))

What is the minimum temperature would you prefer for your trip?70
What is the maximum temperation would you prefer for your trip?90

In [91]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_city_data = city_data_df.loc[(city_data_df['Max Temp']>=min_temp) & \
                                      (city_data_df['Max Temp']<=max_temp)]
preferred_city_data.head(10)

,City ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Current Description,Date
0,0,Saint-Leu,-21.1500,55.2833,70.63,68,30,14.25,RE,scattered clouds,2021-05-21 23:05:46
2,2,Sao Joao Da Barra,-21.6403,-41.0511,73.09,87,7,8.99,BR,clear sky,2021-05-21 23:04:47
6,6,Vanimo,-2.6741,141.3028,81.61,81,100,2.39,PG,overcast clouds,2021-05-21 23:05:47
10,10,Lompoc,34.6391,-120.4579,70.57,64,75,16.11,US,broken clouds,2021-05-21 23:05:48
13,13,Rikitea,-23.1203,-134.9692,76.26,59,30,9.53,PF,scattered clouds,2021-05-21 23:05:49
14,14,Arraial Do Cabo,-22.9661,-42.0278,73.11,86,27,10.45,BR,scattered clouds,2021-05-21 23:03:13
18,18,Albany,42.6001,-73.9662,83.01,78,83,2.51,US,broken clouds,2021-05-21 23:05:20
20,20,Samarai,-10.6167,150.6667,79.99,82,89,15.79,PG,overcast clouds,2021-05-21 23:05:51
21,21,Puerto Ayora,-0.7393,-90.3518,75.54,88,37,8.01,EC,scattered clouds,2021-05-21 23:03:51
23,23,Bethel,41.3712,-73.4140,79.25,48,1,6.91,US,clear sky,2021-05-21 23:03:14

In [92]:
# 4a. Determine if there are any empty rows.
preferred_city_data.isnull()

,City ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Current Description,Date
0,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
678,False,False,False,False,False,False,False,False,False,False,False
681,False,False,False,False,False,False,False,False,False,False,False
686,False,False,False,False,False,False,False,False,False,False,False
688,False,False,False,False,False,False,False,False,False,False,False
694,False,False,False,False,False,False,False,False,False,False,False

In [93]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
new_preferred_city=preferred_city_data.dropna()
new_preferred_city

,City ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Current Description,Date
0,0,Saint-Leu,-21.1500,55.2833,70.63,68,30,14.25,RE,scattered clouds,2021-05-21 23:05:46
2,2,Sao Joao Da Barra,-21.6403,-41.0511,73.09,87,7,8.99,BR,clear sky,2021-05-21 23:04:47
6,6,Vanimo,-2.6741,141.3028,81.61,81,100,2.39,PG,overcast clouds,2021-05-21 23:05:47
10,10,Lompoc,34.6391,-120.4579,70.57,64,75,16.11,US,broken clouds,2021-05-21 23:05:48
13,13,Rikitea,-23.1203,-134.9692,76.26,59,30,9.53,PF,scattered clouds,2021-05-21 23:05:49
...,...,...,...,...,...,...,...,...,...,...,...
678,678,Nagua,19.3832,-69.8474,71.65,87,75,6.78,DO,broken clouds,2021-05-21 23:05:41
681,681,Long,18.0761,99.8326,78.75,81,34,1.74,TH,scattered clouds,2021-05-21 23:05:42
686,686,Ingham,42.6000,-84.3833,84.38,32,1,8.05,US,clear sky,2021-05-21 23:05:43
688,688,Basco,20.4487,121.9702,83.59,81,18,12.50,PH,few clouds,2021-05-21 23:05:44
694,694,Chokwe,-24.5333,32.9833,71.74,70,80,13.76,MZ,broken clouds,2021-05-21 23:05:45

In [94]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = new_preferred_city[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Saint-Leu,RE,70.63,scattered clouds,-21.1500,55.2833,
2,Sao Joao Da Barra,BR,73.09,clear sky,-21.6403,-41.0511,
6,Vanimo,PG,81.61,overcast clouds,-2.6741,141.3028,
10,Lompoc,US,70.57,broken clouds,34.6391,-120.4579,
13,Rikitea,PF,76.26,scattered clouds,-23.1203,-134.9692,
14,Arraial Do Cabo,BR,73.11,scattered clouds,-22.9661,-42.0278,
18,Albany,US,83.01,broken clouds,42.6001,-73.9662,
20,Samarai,PG,79.99,overcast clouds,-10.6167,150.6667,
21,Puerto Ayora,EC,75.54,scattered clouds,-0.7393,-90.3518,
23,Bethel,US,79.25,clear sky,41.3712,-73.4140,

In [95]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    # 6c. Get latitude and longitude from DataFrame

    lat = row['Lat']
    lng = row['Lng']
    params['location']= f'{lat},{lng}'
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = 'https://maps.googleapis.com/maps/api/place/nearbysearch/json'

    # 6e. Make request and retrieve the JSON data from the search. 
    #print(params)
    hotels = requests.get(base_url, params=params).json()
    #print(hotels)
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, 'Hotel Name'] = hotels['results'][0]['name']
    except IndexError: 
        print('City not found...Skipping')

City not found...Skipping
City not found...Skipping
City not found...Skipping
City not found...Skipping
City not found...Skipping
City not found...Skipping
City not found...Skipping
City not found...Skipping
City not found...Skipping
City not found...Skipping
City not found...Skipping
City not found...Skipping
City not found...Skipping
City not found...Skipping
City not found...Skipping
City not found...Skipping
City not found...Skipping
City not found...Skipping
City not found...Skipping
City not found...Skipping
City not found...Skipping

In [101]:
# 7. Drop the rows where there is no Hotel Name
hotel_df['Hotel Name'].replace('', np.nan,inplace = True)

clean_hotel_df = hotel_df.copy()
clean_hotel_df.dropna(inplace = True)

clean_hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Saint-Leu,RE,70.63,scattered clouds,-21.1500,55.2833,La Caz Oceane
2,Sao Joao Da Barra,BR,73.09,clear sky,-21.6403,-41.0511,Pousada Porto De Canoas
6,Vanimo,PG,81.61,overcast clouds,-2.6741,141.3028,Vahmoneh Lodge Vanimo
10,Lompoc,US,70.57,broken clouds,34.6391,-120.4579,"Holiday Inn Express Lompoc, an IHG Hotel"
13,Rikitea,PF,76.26,scattered clouds,-23.1203,-134.9692,Pension Maro'i
...,...,...,...,...,...,...,...
678,Nagua,DO,71.65,broken clouds,19.3832,-69.8474,Hotel Cambri
681,Long,TH,78.75,scattered clouds,18.0761,99.8326,Nopphakoe Homestay
686,Ingham,US,84.38,clear sky,42.6000,-84.3833,Sunset Place
688,Basco,PH,83.59,few clouds,20.4487,121.9702,Nathaniel's Lodge
694,Chokwe,MZ,71.74,broken clouds,-24.5333,32.9833,Complexo Sonho Real

In [107]:
# 8a. Create the output File (CSV)

output_data_file ='../Vacation_Search/WeatherPy_vacation.csv'
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [108]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]
max_temp = clean_hotel_df["Max Temp"]

In [109]:
# 11a. Add a marker layer for each city to the map. 
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4) 
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
# 11b. Display the figure
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
fig

Figure(layout=FigureLayout(height='420px'))